// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkotcjurxywpoflaxipz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrb3RjanVyeHl3cG9mbGF4aXB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTA2MjcsImV4cCI6MjA2NTI4NjYyN30.KFaTtUucMo9i0RPdueWa7I0qf8pstU-64sRJHGi2jyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);